#!/usr/bin/env bash

wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_01
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_02
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_03
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_04
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_05
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_06
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_07
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_08
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_09
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_10
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_11
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/normals/normal_12
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_01
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_02
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_03
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_04
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_05
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_06
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_07
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_08
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_09
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_10
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_11
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_12
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_13
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_14
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/cancers/cancer_15
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_01
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_02
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_03
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_04
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_05
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_06
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_07
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_08/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_09/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_10/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_11/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_12
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_13/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benigns/benign_14/
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benign_without_callbacks/benign_without_callback_01
wget -r ftp://figment.csee.usf.edu/pub/DDSM/cases/benign_without_callbacks/benign_without_callback_02
